import {
    AcademicCapIcon,
    AdjustmentsHorizontalIcon,
    ArchiveBoxIcon,
    BellIcon,
    BookmarkIcon,
    BriefcaseIcon,
    CalendarIcon,
    ChartBarIcon,
    ChatBubbleLeftRightIcon,
    CheckIcon,
    ClipboardDocumentIcon,
    CloudIcon,
    Cog6ToothIcon,
    CubeIcon,
    DocumentTextIcon,
    HeartIcon,
    HomeIcon,
    InboxIcon,
    LightBulbIcon,
    SparklesIcon,
    MicrophoneIcon
  } from '@heroicons/vue/24/outline'
  
  export const iconOptions = {
    AcademicCapIcon,
    AdjustmentsHorizontalIcon,
    ArchiveBoxIcon,
    BellIcon,
    BookmarkIcon,
    BriefcaseIcon,
    CalendarIcon,
    ChartBarIcon,
    ChatBubbleLeftRightIcon,
    CheckIcon,
    ClipboardDocumentIcon,
    CloudIcon,
    Cog6ToothIcon,
    CubeIcon,
    DocumentTextIcon,
    HeartIcon,
    HomeIcon,
    InboxIcon,
    LightBulbIcon,
    SparklesIcon,
    MicrophoneIcon
  }  